controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
calculate_price:
    path: /calculate-price
    controller: App\Controller\ProductController::calculatePrice
    methods: [POST]

purchase:
    path: /purchase
    controller: App\Controller\ProductController::purchase
    methods: [POST]